#!/bin/bash

case "$1" in
  start)
    $PWD/boot/mongo start
    ;;
  stop)
    $PWD/boot/mongo stop
    ;;
  restart)
    $PWD/boot/db stop
    $PWD/boot/db start
    ;;
  status)
    $PWD/boot/mongo status
    ;;
esac
