# Nginx
#
# VERSION               0.0.1
#
FROM      ubuntu
MAINTAINER Cajun "zac@kleinpeter.org"
#
# make sure the package repository is up to date
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv 7F0CEB10
RUN echo "deb http://archive.ubuntu.com/ubuntu precise main universe" > /etc/apt/sources.list
RUN echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | tee /etc/apt/sources.list.d/10gen.list
RUN apt-get update
RUN apt-get install -y mongodb-10gen
EXPOSE 27017

RUN apt-get clean; apt-get autoclean; apt-get autoremove
