#!/bin/bash

ME=$(basename $0)
APP="`basename $PWD`"
CONTAINER='praeses/ruby_1.9.3:xorg'
REMOTE_VOLUMN='/www'
VOLUMNS="-v $PWD:$REMOTE_VOLUMN"
PORT=5000
START_COMMAND="/bin/bash -c 'cd $REMOTE_VOLUMN && ./bin/unicorn -p $PORT -c ./config/unicorn.rb'"
OPTIONS="-d -p $PORT"
DOMAIN="`echo $APP`.dev"

source $PWD/boot/common/base
source $PWD/boot/common/rails
