# Nginx
#
# VERSION               0.0.1
#
FROM      ubuntu
MAINTAINER Cajun "zac@kleinpeter.org"
RUN echo "deb http://archive.ubuntu.com/ubuntu precise main universe" > /etc/apt/sources.list
RUN echo "deb http://archive.ubuntu.com/ubuntu precise main multiverse" > /etc/apt/sources.list
RUN apt-get update
RUN apt-get install -y python-software-properties python g++ make
RUN apt-get update
RUN apt-get install -y wget

#Fix for heartbleet
RUN wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl/openssl_1.0.1-4ubuntu5.12_amd64.deb
RUN wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.0.0_1.0.1-4ubuntu5.12_amd64.deb
RUN wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl-dev_1.0.1-4ubuntu5.12_amd64.deb
RUN dpkg -i libssl1.0.0_1.0.1-4ubuntu5.12_amd64.deb openssl_1.0.1-4ubuntu5.12_amd64.deb
RUN apt-get -y install zlib1g-dev
RUN dpkg -i libssl-dev_1.0.1-4ubuntu5.12_amd64.deb


RUN apt-get install -y wget build-essential libreadline6 libreadline6-dev curl git-core zlib1g zlib1g-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt-dev autoconf libc6-dev ncurses-dev automake libtool bison subversion
RUN git clone git://github.com/ry/node.git; cd node; ./configure; make; make install

RUN apt-get upgrade -y

RUN wget ftp://ftp.ruby-lang.org/pub/ruby/2.0/ruby-2.0.0-p247.tar.gz; tar xvfz ruby-2.0.0-p247.tar.gz
RUN cd /ruby-2.0.0-p247; ./configure && make && make install
RUN gem update --system --no-rdoc --no-ri; gem install bundler --no-rdoc --no-ri

RUN apt-get install -y xvfb imagemagick  freetds-dev --fix-missing
RUN apt-get clean
