FROM      ubuntu
MAINTAINER Cajun "zac@kleinpeter.org"
#
# make sure the package repository is up to date
RUN echo "deb http://archive.ubuntu.com/ubuntu precise main universe" > /etc/apt/sources.list
RUN apt-get update
RUN apt-get -y install mysql-server

RUN echo "[mysqld]\nbind-address=0.0.0.0" > /etc/mysql/conf.d/mysql-listen.cnf
