# Nginx
#
# VERSION               0.0.1
#
FROM      ubuntu
MAINTAINER Cajun "zac@kleinpeter.org"
#
# make sure the package repository is up to date
RUN echo "deb http://archive.ubuntu.com/ubuntu precise main universe" > /etc/apt/sources.list
RUN apt-get update
RUN apt-get install -y python-software-properties
RUN add-apt-repository ppa:gophers/go
RUN apt-get update

VOLUME ['/gocode']
ENV GOPATH /gocode
ENV PATH $GOPATH/bin;$PATH

RUN apt-get install -y golang-stable


