#!/bin/bash

source $PWD/boot/common/ruby

function updateNginx {
    cmd="sed -e 's:%APP%:$APP:g'
    -e 's:%PWD%:$PWD:g' \
      -e 's:%PORT%:$PUBLIC_PORT:g' \
      -e 's:%DOMAINS%:$DOMAIN:g' \
      -e 's:%ALLOW%:
          allow 192.168.102.0/24;\n
          allow 192.168.101.0/24;\n
          allow 192.168.100.0/24;\n:g' \
      $PWD/config/nginx.template.conf > $PWD/config/nginx.conf"
    echo $cmd
    eval $cmd

}
case "$1" in
  rails)
    START_COMMAND="/bin/bash -c 'cd $REMOTE_VOLUMN && ./bin/rails ${@:2}'"
    run_interactive
  ;;
  assets)
    $PWD/boot/rake assets:clean assets:precompile
  ;;
  console)
    $PWD/boot/$ME rails console
  ;;
  start)
    # This will run the generic start boot
    updateNginx
    echo "Reloading nginx"
    sudo nginx -s reload
  ;;
  conf)
    updateNginx
  ;;
esac
